version: '2'
services:
  db:
    image: postgres:9.6
    volumes:
      - ./backups:/backups
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
     - backend

  redis:
    image: redis:3.2
    networks:
     - backend

  rails: &rails
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
     - backend
    # env_file:
    #   - .env
    volumes:
      - .:/web
      - ./backups:/backups
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis.local:6379
      - REDIS_PROVIDER=redis://redis.local:6379
      - REDIS_HOST=redis.local
      - REDIS_PORT=6379

      - DATABASE_HOST=db.local
      - DATABASE_NAME=development
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432

      - SIDEKIQ_USERNAME=devuser
      - SIDEKIQ_PASSWORD=1234

  web:
    <<: *rails
    command: bundle exec rails s -p 4401 -b '0.0.0.0'
    # command: bundle exec puma -C ./config/puma.rb -b tcp://0.0.0.0:4301
    ports:
      - "4401:4401"
    links:
      - db
      # - worker
      - db:db.local
      - redis
      - redis:redis.local

  # worker:
  #   <<: *rails
  #   command: bundle exec sidekiq
  #   links:
  #     - db
  #     - db:db.local
  #     - redis
  #     - redis:redis.local

networks:
  backend:
    driver: bridge
